name: CI/CD for Stock Api Project
on:
  push:
    paths-ignore:
      - ".github/**"
      - "readme-images/**"
      - "**.md"
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .Net 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore

      - name: Run unit tests
        run: dotnet test

      - name: .NET code metrics
        id: dotnet-code-metrics
        uses: dotnet/samples/github-actions/DotNet.GitHubAction@main
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ github.repository }}
          branch: ${{ github.ref }}
          dir: ${{ './github-actions/DotNet.GitHubAction' }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.4.1
        if: ${{ steps.dotnet-code-metrics.outputs.updated-metrics }} == 'true'
        with:
          title: "${{ steps.dotnet-code-metrics.outputs.summary-title }}"
          body: "${{ steps.dotnet-code-metrics.outputs.summary-details }}"
          commit-message: ".NET code metrics, automated pull request."
