name: CI/CD for Stock Api Project
on:
  push:
    paths-ignore:
      - ".github/**"
      - "readme-images/**"
      - "README.md"
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .Net 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore

      - name: Run unit tests
        run: dotnet test
